base_url: https://finance.yahoo.com/quote/{ticker}/news/
headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  Accept: "text/html,application/xhtml+xml,application/xml;q=0.9"
  Accept-Language: "en-US,en;q=0.9"
timeout: 30
max_articles: 10
retry_attempts: 3