name: Python Linter

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint black isort

      - name: Check code formatting with Black
        run: black --check .
        
      - name: Sort imports with isort
        run: isort --check-only --diff .
        
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
          
      - name: Lint with pylint
        run: |
          pylint $(git ls-files '*.py') --disable=C,R,W